server:
  port: 8080

spring:
  h2:
    console:
      enabled: true 
      path: /h2-console 
  datasource:
    url: jdbc:h2:mem:memdb 
    username: sa 
    password: 
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #dialect: org.hib
        format-sql: true 
        jdbc:
          lob:
            non-contextual-creation: true 
  output:
    ansi:
      enabled: always